### ISSUE TITLE
Add option to remove existing texts for logged in users

### ISSUE THREAD

**Issue by yuvraj108c** [goldylucks/typing#147]
It is difficult to find which texts I have created, as there are so many pre-existing ones. So, add option to remove unnecessary texts

**Comment by goldylucks** [comment]
oh wow you are using this app? Very cool :)

As you can see it's been long since I've made any changes for it :see_no_evil: You are more than welcome to send a PR. I'll guide you the best I can if you have any Qs.

I think a better way to handle this is with filters instead of removing other users' texts.

Thoughts?

**Comment by yuvraj108c** [comment]
I'm new to node.js. I know only vanilla js and php. So, I do not know how to modify the code
